# Generated by Django 5.1.3 on 2025-02-08 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('especialidad', models.CharField(max_length=200)),
                ('contacto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('estado', models.CharField(choices=[('planeado', 'Planeado'), ('en_construccion', 'En Construcción'), ('finalizado', 'Finalizado')], default='planeado', max_length=20)),
                ('presupuesto_asignado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('constructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Publicas.constructor')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_asignado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Publicas.obra')),
            ],
        ),
    ]
