# Generated by Django 5.1.3 on 2025-02-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_constructores/'),
        ),
    ]
