# Generated by Django 5.1.3 on 2025-02-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publicas', '0002_constructor_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='monto_gastado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='monto_asignado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
